# Tranquilpeak
# Version : 0.1.4-ALPHA
# Author : Thibaud Leprêtre

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/images` folder and
# use grunt task `build` to synchronize assets

baseurl = "https://jeffersonheard.github.io/"
languageCode = "en-us"
title = "Jefferson Heard"
theme = "hugo-strata-theme"
DisqusShortname = "jeffersonheard-github-io"
googleAnalytics = "UA-68674847-2"
Paginate = 7
canonifyurls = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Jefferson Heard"
  bio = "Technologist, CTO, experimental cook, hiker"
  job = "CTO, [365 Pronto](https://www.365pronto.com)"
  location = "NC USA"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  # gravatar_email = "jefferson.r.heard@gmail.com"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatar` is filled
  picture = "img/portrait.jpg"
  # Your Twitter username without the @. E.g : thibaudlepretre
  # twitter = "thibaudlepretre"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
  # google_plus = "+ThibaudLepretre"

# Menu Configuration
[[menu.main]]
  weight = 0
  identifier = "home"
  name = "Home"
  url = "/"

[[menu.main]]
  weight = 2
  identifier = "blog"
  name = "Blog"
  url = "/post"

[[menu.main]]
  weight = 1
  identifier = "about"
  name = "About"
  url = "/about"

[[menu.misc]]
  weight = 3
  identifier = "consulting"
  name = "Consulting"
  url = "/consulting"

[[menu.main]]
  weight = 4
  identifier = "resume"
  name = "Resume"
  url = "/resume.pdf"

[[menu.main]]
  weight = 5
  identifier = "cv"
  name = "CV"
  url = "/cv.pdf"

[[menu.main]]
  weight = 7
  identifier = "sondra"
  name = "Sondra Docs"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://jeffersonheard.github.io/sondra"

[[menu.main]]
  weight = 6
  identifier = "pronto"
  name = "365 Pronto"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-briefcase\"></i>"
  url = "https://www.365pronto.com"


[params]
  # Global keywords configuration. Following keywords will be add to every pages
  # keywords = ["development", "next-gen"]

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clear_reading = true

  hierarchical_categories = false

  date_format = "2006-01-02"

  description = "Personal and professional website of Jefferson Heard"

  [params.about]
		hide  = false
		title = "Versatile data scientist and software consultant specializing in collaboration tools, APIs, geospatial data, and visualization."
		content = '''### Solutions

<span class="callout">Interactive, custom web-mapping makes your mobile-based app stand out from the crowd.</span>
I can take your data and make it sing to your customers. My solutions are scalable and
work on your website, in your mobile app, or in your application.

<span class="callout">Custom data science for business insights and academic work.</span> I can take complex data and methods and turn them into code and analysis for repeatable, high-performance insights.

<span class="callout">Customized open-source collaboration tools.</span> I can make your data accessible and open to your team and to far-flung colleagues using open source tools for information, knowledge management, and deeply customized content sharing.

### Testimonials

>Jeff understood quickly what we wanted, scrubbed our messy data, and produced a custom map that was exactly what we wanted--and on time.
**(Lisa Chensvold. Director of Communications [International Executive Service Corps](http://www.iesc.org)**)
'''


	[params.portfolio]
		hide  = false
		title = "Project Portfolio"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/lebanon.pdf"
			thumb = "thumbs/lebanon.png"
			title = "Financial Inclusion in Lebanon."
			description = """**Client:** International Executive Service Corps. http://iesc.org.

  **Task:** Create a publication quality map that shows the current distribution of microfinance institutions in Lebanon, for the purposes of presenting to a granting body. **(2016)**

  **Reference Contact:** [Lisa Chensvold. Director of Communications](https://www.linkedin.com/in/lisachensvold)."""

		[[params.portfolio.gallery]]
			link = "https://jeffersonheard.github.io/sondra"
			thumb = "thumbs/sondra.svg"
			title = "Sondra."
			description = "An ORM and API generator for RethinkDB, Python 3, and Flask."

		[[params.portfolio.gallery]]
			link = "https://github.com/jeffersonheard/terrapyn"
			thumb = "thumbs/terrapyn.png"
			title = "Terrapyn Geospatial CMS."
			description = "An Open Source CMS and API for geospatial data, built using Python, Django, and Open Source geospatial tools."

		[[params.portfolio.gallery]]
			link = "https://hydroshare.org"
			thumb = "thumbs/hydroshare.png"
      title = "Hydroshare (project technical lead while at RENCI)."
			description = "An Open Source CMS and API for hydrological data."

  [params.sidebar]
    # Replace the avatar with a picture of your own under static/images
    avatar = "portrait.jpg"
    # Use Markdown to format the string. This works nearly all over the theme
    bio = "**CTO & Data Science Consultant**"
    # The icons will be shown if you enter your username
    twitter = "jeffersonheard"
    github = "jeffersonheard"
    dribbble = ""
    facebook = ""
    googleplus = ""
    flickr = ""
    linkedin = "https://linkedin.com/injeffersonheard"

    copyright = [
      "&copy; 2016 Jefferson Heard",

    ]

  [params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Contact me about consulting, interviews, or talks"
		content = "I am available for consulting, talks, and short-courses on mapping, geography, and open source software. For more information about what I do, <a href='consulting'>see my consulting page</a>."

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "jefferson.r.heard@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Your name"
			email = "Your email"
			message = "Ask me a question!"
			submit = "Send"
